import { describe, expect, it } from "vitest";

import {
  bindGeneratedClaims,
  createVerificationSnapshot,
  evaluateVerificationGenerationGate,
  type VerificationClaimSpec,
  type VerificationSourceAssessment,
} from "../../../../core/approval";
import { createContentOpportunityVerificationPlan, type ContentDocument } from "../../../../core/content";

const claim: VerificationClaimSpec = Object.freeze({
  claimId: "claim-amount",
  field: "amount",
  kind: "money",
  statement: "현재 지원 금액은 50만원이다.",
  rawValue: "50만원",
  qualifiers: Object.freeze({}),
  temporalRequirement: Object.freeze({ mode: "current" as const }),
  required: true,
});

const plan = createContentOpportunityVerificationPlan([claim]);
const normalizedValue = Object.freeze({
  kind: "money" as const,
  value: Object.freeze({
    amount: 500_000,
    currency: "KRW",
    basis: "total" as const,
  }),
});

function assessment(
  sourceId: string,
  role: VerificationSourceAssessment["role"],
): VerificationSourceAssessment {
  return Object.freeze({
    sourceId,
    institutionGroupId: `institution-${sourceId}`,
    canonicalUrl: `https://${sourceId}.example/claim`,
    role,
    authoritative: true,
    supports: true,
    normalizedValue,
    freshnessStatus: "fresh" as const,
    fresh: true,
    diagnostics: Object.freeze([`claim:${claim.claimId}`]),
  });
}

function verificationContext() {
  const assessments = Object.freeze([
    assessment("primary", "primaryOfficial"),
    assessment("official-a", "officialCorroborating"),
    assessment("official-b", "officialCorroborating"),
  ]);
  const snapshot = createVerificationSnapshot({
    plan,
    assessments,
    results: [{
      claimId: claim.claimId,
      normalizedValue,
      sourceAssessments: assessments,
      unresolvedConflict: false,
      freshnessPassed: true,
      diagnostics: [],
    }],
  });
  const gate = evaluateVerificationGenerationGate({ plan, snapshot });
  expect(gate.ready).toBe(true);
  return { snapshot, gate };
}

function documentWith(text: string, metadata?: ContentDocument["metadata"]): ContentDocument {
  return Object.freeze({
    id: "content-1",
    title: "지원 금액 확인 방법",
    blocks: Object.freeze([
      Object.freeze({ id: "p1", type: "paragraph" as const, text }),
    ]),
    ...(metadata ? { metadata } : {}),
  });
}

describe("Generated Claim binding", () => {
  it("binds an exact generated value to the verified Claim and its trusted sources", () => {
    const { snapshot, gate } = verificationContext();
    const result = bindGeneratedClaims({
      document: documentWith("현재 지원 금액은 50만원입니다."),
      plan,
      snapshot,
      gate,
    });

    expect(result.unverifiedDetectedCount).toBe(0);
    expect(result.verifiedClaimIds).toEqual([claim.claimId]);
    expect(result.bindings).toContainEqual({
      location: { kind: "block", blockId: "p1" },
      matchedText: "50만원",
      reference: {
        referenceType: "verified",
        verificationClaimId: claim.claimId,
        sourceIds: ["primary", "official-a", "official-b"],
      },
    });
  });

  it("binds a deterministic equivalent money representation without trusting AI labels", () => {
    const { snapshot, gate } = verificationContext();
    const result = bindGeneratedClaims({
      document: documentWith("현재 지원 금액은 500,000원입니다."),
      plan,
      snapshot,
      gate,
    });

    expect(result.unverifiedDetectedCount).toBe(0);
    expect(result.bindings.some((binding) =>
      binding.reference.referenceType === "verified"
      && binding.reference.verificationClaimId === claim.claimId)).toBe(true);
  });

  it("marks an unsupported high-risk scalar generated by the manuscript as unverifiedDetected", () => {
    const { snapshot, gate } = verificationContext();
    const result = bindGeneratedClaims({
      document: documentWith("현재 지원 금액은 70만원입니다."),
      plan,
      snapshot,
      gate,
    });

    expect(result.verifiedClaimIds).toEqual([]);
    expect(result.bindings).toContainEqual({
      location: { kind: "block", blockId: "p1" },
      matchedText: "70만원",
      reference: {
        referenceType: "unverifiedDetected",
        diagnosticCode: "unverified_generated_money",
      },
    });
  });

  it("does not treat ordinary structural numbers as external high-risk facts", () => {
    const { snapshot, gate } = verificationContext();
    const result = bindGeneratedClaims({
      document: documentWith("확인할 항목은 3가지입니다. 1단계부터 순서대로 확인하세요."),
      plan,
      snapshot,
      gate,
    });

    expect(result.bindings).toEqual([]);
    expect(result.unverifiedDetectedCount).toBe(0);
  });

  it("also binds verified values when they appear in publishable SEO metadata", () => {
    const { snapshot, gate } = verificationContext();
    const metadata: NonNullable<ContentDocument["metadata"]> = Object.freeze({
      buttonCount: 0,
      createdAt: "2026-08-08T00:00:00.000Z",
      generator: "test",
      imageCount: 0,
      language: "ko",
      readingTime: 1,
      source: "ai",
      updatedAt: "2026-08-08T00:00:00.000Z",
      version: 1,
      videoCount: 0,
      wordCount: 5,
      seoTitle: "지원 금액 50만원 확인 방법",
      metaDescription: "현재 지원 금액 50만원과 공식 확인 경로를 안내합니다.",
    });
    const result = bindGeneratedClaims({
      document: documentWith("공식 안내에서 적용 조건을 확인하세요.", metadata),
      plan,
      snapshot,
      gate,
    });

    expect(result.bindings.some((binding) =>
      binding.location.kind === "metadata"
      && binding.reference.referenceType === "verified")).toBe(true);
  });
});
