"use client";

import { useEffect, useState } from "react";

type Impact = Readonly<{ name: string; brandCount: number; projectCount: number; contentCount: number; draftCount: number; historyCount: number; mediaCount: number; qualityReportCount: number; publishingRecordCount: number; scheduleRecordCount: number; publishingAccountCount: number }>;

export function DangerZone({ scope, workspaceId, projectId, onDeleted }: { scope: "project" | "workspace"; workspaceId: string; projectId?: string; onDeleted: () => void }) {
  const [open, setOpen] = useState(false), [impact, setImpact] = useState<Impact>(); const [confirmation, setConfirmation] = useState(""); const [finalConfirmation, setFinalConfirmation] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { if (!open) return; void call({ action: `${scope}-impact`, workspaceId, projectId }).then((result) => setImpact(result.impact as Impact)).catch((error) => setNotice(message(error))); }, [open, projectId, scope, workspaceId]);
  const remove = async () => { try { const result = await call({ action: `delete-${scope}`, workspaceId, projectId, confirmation, finalConfirmation }); if (result.status === "cleanup_required") { setNotice(`Cleanup required: ${String(result.error)}`); return; } setNotice(`Deleted after backup ${String(result.backupName)}.`); onDeleted(); } catch (error) { setNotice(message(error)); } };
  return <section className="mt-8 rounded-[20px] border border-red-200 bg-red-50/40 p-5"><h2 className="font-semibold text-red-800">Danger Zone</h2><p className="mt-2 text-sm text-red-700">Local deletion creates a versioned backup first and never deletes external platform content.</p><button className="mt-3 rounded-xl border border-red-300 bg-white px-4 py-2.5 text-sm font-semibold text-red-800" onClick={() => setOpen((value) => !value)} type="button">Delete {scope}</button>
    {open && impact ? <div className="mt-4 rounded-xl bg-white p-4"><h3 className="font-semibold">Deletion impact for {impact.name}</h3><ul className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><li>Brands: {impact.brandCount}</li><li>Projects: {impact.projectCount}</li><li>Contents: {impact.contentCount}</li><li>Drafts: {impact.draftCount}</li><li>History: {impact.historyCount}</li><li>Media: {impact.mediaCount}</li><li>Quality Reports: {impact.qualityReportCount}</li><li>Publishing records: {impact.publishingRecordCount}</li><li>Schedules: {impact.scheduleRecordCount}</li><li>Publishing Accounts: {impact.publishingAccountCount}</li></ul><label className="mt-4 block text-sm font-semibold">Type <strong>{impact.name}</strong> exactly<input className="mt-2 w-full rounded-xl border px-4 py-3 font-normal" onChange={(event) => setConfirmation(event.target.value)} value={confirmation} /></label>{scope === "workspace" ? <label className="mt-3 flex gap-3 text-sm"><input checked={finalConfirmation} onChange={(event) => setFinalConfirmation(event.target.checked)} type="checkbox" />Final confirmation: remove this Workspace and its local metadata. External content will remain.</label> : null}<button className="mt-4 rounded-xl bg-red-700 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40" disabled={confirmation !== impact.name || (scope === "workspace" && !finalConfirmation)} onClick={() => void remove()} type="button">Permanently delete local {scope}</button></div> : null}<p aria-live="polite" className="mt-3 text-sm text-red-800">{notice}</p>
  </section>;
}

async function call(body: unknown) { const response = await fetch("/api/deletion", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as Record<string, unknown>; if (!response.ok && result.status !== "cleanup_required") throw new Error(String(result.error ?? "Deletion failed.")); return result; }
function message(error: unknown) { return error instanceof Error ? error.message : "Deletion failed."; }
